FROM trufflesuite/ganache-cli:v6.12.2
LABEL maintainer="team@cere.network"
LABEL description="This is the build stage for copy snapshot and artifacts to official ganache cli image"

COPY ./artifacts /app
